repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
        language_version: python3.6
    -   id: end-of-file-fixer
        language_version: python3.6
    -   id: autopep8-wrapper
        language_version: python3.6
    -   id: requirements-txt-fixer
        language_version: python3.6
    -   id: flake8
        language_version: python3.6
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
